const COUNTRIES = [
  {en:"Afghanistan",ro:"Afghanistan",alt:[],id:4},
  {en:"Albania",ro:"Albania",alt:[],id:8},
  {en:"Algeria",ro:"Algeria",alt:[],id:12},
  {en:"Angola",ro:"Angola",alt:[],id:24},
  {en:"Argentina",ro:"Argentina",alt:[],id:32},
  {en:"Armenia",ro:"Armenia",alt:[],id:51},
  {en:"Australia",ro:"Australia",alt:[],id:36},
  {en:"Austria",ro:"Austria",alt:[],id:40},
  {en:"Azerbaijan",ro:"Azerbaijan",alt:[],id:31},
  {en:"Bangladesh",ro:"Bangladesh",alt:[],id:50},
  {en:"Belarus",ro:"Belarus",alt:[],id:112},
  {en:"Belgium",ro:"Belgia",alt:[],id:56},
  {en:"Benin",ro:"Benin",alt:[],id:204},
  {en:"Bolivia",ro:"Bolivia",alt:[],id:68},
  {en:"Bosnia and Herzegovina",ro:"Bosnia și Herțegovina",alt:["Bosnia"],id:70},
  {en:"Botswana",ro:"Botswana",alt:[],id:72},
  {en:"Brazil",ro:"Brazilia",alt:[],id:76},
  {en:"Bulgaria",ro:"Bulgaria",alt:[],id:100},
  {en:"Burkina Faso",ro:"Burkina Faso",alt:[],id:854},
  {en:"Burundi",ro:"Burundi",alt:[],id:108},
  {en:"Cambodia",ro:"Cambodgia",alt:[],id:116},
  {en:"Cameroon",ro:"Camerun",alt:[],id:120},
  {en:"Canada",ro:"Canada",alt:[],id:124},
  {en:"Central African Republic",ro:"Republica Centrafricană",alt:["RCA"],id:140},
  {en:"Chad",ro:"Ciad",alt:[],id:148},
  {en:"Chile",ro:"Chile",alt:[],id:152},
  {en:"China",ro:"China",alt:[],id:156},
  {en:"Colombia",ro:"Columbia",alt:[],id:170},
  {en:"Congo",ro:"Congo",alt:[],id:178},
  {en:"Croatia",ro:"Croația",alt:["Croatia"],id:191},
  {en:"Cuba",ro:"Cuba",alt:[],id:192},
  {en:"Czech Republic",ro:"Cehia",alt:[],id:203},
  {en:"Denmark",ro:"Danemarca",alt:[],id:208},
  {en:"Dominican Republic",ro:"Republica Dominicană",alt:[],id:214},
  {en:"DR Congo",ro:"Rep. Dem. Congo",alt:["RDC","Congo Democrat"],id:180},
  {en:"Ecuador",ro:"Ecuador",alt:[],id:218},
  {en:"Egypt",ro:"Egipt",alt:[],id:818},
  {en:"El Salvador",ro:"El Salvador",alt:[],id:222},
  {en:"Eritrea",ro:"Eritreea",alt:[],id:232},
  {en:"Estonia",ro:"Estonia",alt:[],id:233},
  {en:"Ethiopia",ro:"Etiopia",alt:[],id:231},
  {en:"Finland",ro:"Finlanda",alt:[],id:246},
  {en:"France",ro:"Franța",alt:["Franta"],id:250},
  {en:"Gabon",ro:"Gabon",alt:[],id:266},
  {en:"Georgia",ro:"Georgia",alt:[],id:268},
  {en:"Germany",ro:"Germania",alt:[],id:276},
  {en:"Ghana",ro:"Ghana",alt:[],id:288},
  {en:"Greece",ro:"Grecia",alt:[],id:300},
  {en:"Guatemala",ro:"Guatemala",alt:[],id:320},
  {en:"Guinea",ro:"Guineea",alt:[],id:324},
  {en:"Honduras",ro:"Honduras",alt:[],id:340},
  {en:"Hungary",ro:"Ungaria",alt:[],id:348},
  {en:"Iceland",ro:"Islanda",alt:[],id:352},
  {en:"India",ro:"India",alt:[],id:356},
  {en:"Indonesia",ro:"Indonezia",alt:[],id:360},
  {en:"Iran",ro:"Iran",alt:[],id:364},
  {en:"Iraq",ro:"Irak",alt:[],id:368},
  {en:"Ireland",ro:"Irlanda",alt:[],id:372},
  {en:"Israel",ro:"Israel",alt:[],id:376},
  {en:"Italy",ro:"Italia",alt:[],id:380},
  {en:"Ivory Coast",ro:"Coasta de Fildeș",alt:["Cote d Ivoire"],id:384},
  {en:"Jamaica",ro:"Jamaica",alt:[],id:388},
  {en:"Japan",ro:"Japonia",alt:[],id:392},
  {en:"Jordan",ro:"Iordania",alt:[],id:400},
  {en:"Kazakhstan",ro:"Kazahstan",alt:[],id:398},
  {en:"Kenya",ro:"Kenya",alt:[],id:404},
  {en:"Kosovo",ro:"Kosovo",alt:[],id:383},
  {en:"Kuwait",ro:"Kuweit",alt:[],id:414},
  {en:"Kyrgyzstan",ro:"Kârgâzstan",alt:["Kirgizstan"],id:417},
  {en:"Laos",ro:"Laos",alt:[],id:418},
  {en:"Latvia",ro:"Letonia",alt:[],id:428},
  {en:"Lebanon",ro:"Liban",alt:[],id:422},
  {en:"Liberia",ro:"Liberia",alt:[],id:430},
  {en:"Libya",ro:"Libia",alt:[],id:434},
  {en:"Lithuania",ro:"Lituania",alt:[],id:440},
  {en:"Luxembourg",ro:"Luxemburg",alt:[],id:442},
  {en:"Madagascar",ro:"Madagascar",alt:[],id:450},
  {en:"Malawi",ro:"Malawi",alt:[],id:454},
  {en:"Malaysia",ro:"Malaysia",alt:[],id:458},
  {en:"Mali",ro:"Mali",alt:[],id:466},
  {en:"Mauritania",ro:"Mauritania",alt:[],id:478},
  {en:"Mexico",ro:"Mexic",alt:[],id:484},
  {en:"Moldova",ro:"Moldova",alt:[],id:498},
  {en:"Mongolia",ro:"Mongolia",alt:[],id:496},
  {en:"Morocco",ro:"Maroc",alt:[],id:504},
  {en:"Mozambique",ro:"Mozambic",alt:[],id:508},
  {en:"Myanmar",ro:"Myanmar",alt:["Birmania"],id:104},
  {en:"Namibia",ro:"Namibia",alt:[],id:516},
  {en:"Nepal",ro:"Nepal",alt:[],id:524},
  {en:"Netherlands",ro:"Olanda",alt:["Tarile de Jos"],id:528},
  {en:"New Zealand",ro:"Noua Zeelandă",alt:["Noua Zeelanda"],id:554},
  {en:"Nicaragua",ro:"Nicaragua",alt:[],id:558},
  {en:"Niger",ro:"Niger",alt:[],id:562},
  {en:"Nigeria",ro:"Nigeria",alt:[],id:566},
  {en:"North Korea",ro:"Coreea de Nord",alt:[],id:408},
  {en:"North Macedonia",ro:"Macedonia de Nord",alt:["Macedonia"],id:807},
  {en:"Norway",ro:"Norvegia",alt:[],id:578},
  {en:"Oman",ro:"Oman",alt:[],id:512},
  {en:"Pakistan",ro:"Pakistan",alt:[],id:586},
  {en:"Panama",ro:"Panama",alt:[],id:591},
  {en:"Papua New Guinea",ro:"Papua Noua Guinee",alt:[],id:598},
  {en:"Paraguay",ro:"Paraguay",alt:[],id:600},
  {en:"Peru",ro:"Peru",alt:[],id:604},
  {en:"Philippines",ro:"Filipine",alt:[],id:608},
  {en:"Poland",ro:"Polonia",alt:[],id:616},
  {en:"Portugal",ro:"Portugalia",alt:[],id:620},
  {en:"Romania",ro:"România",alt:["Romania"],id:642},
  {en:"Russia",ro:"Rusia",alt:[],id:643},
  {en:"Rwanda",ro:"Rwanda",alt:[],id:646},
  {en:"Saudi Arabia",ro:"Arabia Saudită",alt:["Arabia Saudita"],id:682},
  {en:"Senegal",ro:"Senegal",alt:[],id:686},
  {en:"Serbia",ro:"Serbia",alt:[],id:688},
  {en:"Sierra Leone",ro:"Sierra Leone",alt:[],id:694},
  {en:"Slovakia",ro:"Slovacia",alt:[],id:703},
  {en:"Slovenia",ro:"Slovenia",alt:[],id:705},
  {en:"Somalia",ro:"Somalia",alt:[],id:706},
  {en:"South Africa",ro:"Africa de Sud",alt:[],id:710},
  {en:"South Korea",ro:"Coreea de Sud",alt:[],id:410},
  {en:"South Sudan",ro:"Sudanul de Sud",alt:[],id:728},
  {en:"Spain",ro:"Spania",alt:[],id:724},
  {en:"Sri Lanka",ro:"Sri Lanka",alt:[],id:144},
  {en:"Sudan",ro:"Sudan",alt:[],id:729},
  {en:"Sweden",ro:"Suedia",alt:[],id:752},
  {en:"Switzerland",ro:"Elveția",alt:["Elvetia"],id:756},
  {en:"Syria",ro:"Siria",alt:[],id:760},
  {en:"Tajikistan",ro:"Tadjikistan",alt:[],id:762},
  {en:"Tanzania",ro:"Tanzania",alt:[],id:834},
  {en:"Thailand",ro:"Thailanda",alt:[],id:764},
  {en:"Togo",ro:"Togo",alt:[],id:768},
  {en:"Tunisia",ro:"Tunisia",alt:[],id:788},
  {en:"Turkey",ro:"Turcia",alt:[],id:792},
  {en:"Turkmenistan",ro:"Turkmenistan",alt:[],id:795},
  {en:"Uganda",ro:"Uganda",alt:[],id:800},
  {en:"Ukraine",ro:"Ucraina",alt:[],id:804},
  {en:"United Arab Emirates",ro:"Emiratele Arabe Unite",alt:["EAU","UAE"],id:784},
  {en:"United Kingdom",ro:"Marea Britanie",alt:["UK","Regatul Unit"],id:826},
  {en:"United States of America",ro:"SUA",alt:["Statele Unite","America","USA"],id:840},
  {en:"Uruguay",ro:"Uruguay",alt:[],id:858},
  {en:"Uzbekistan",ro:"Uzbekistan",alt:[],id:860},
  {en:"Venezuela",ro:"Venezuela",alt:[],id:862},
  {en:"Vietnam",ro:"Vietnam",alt:[],id:704},
  {en:"Yemen",ro:"Yemen",alt:[],id:887},
  {en:"Zambia",ro:"Zambia",alt:[],id:894},
  {en:"Zimbabwe",ro:"Zimbabwe",alt:[],id:716}
];
